module.exports = {
    REQUEST_DENIED: "Request Denied",
    SERVER_UNDER_MAINTENANCE: "Server Under Maintenance",
    ROUTE_NOT_FOUND: "Route Not Found",
    KEY_DEVICE_FINGER_PRINT: "device-finger-print",
    KEY_DEVICE_DESCRIPTION: "device-description",
    KEY_AUTHENTICATION_TOKEN: "authentication-token",
    ERROR_DEVICE_MISSING: "Device Information Is Missing",

    CACHE_KEY_COURSE_CATEGORIES: "CACHE_KEY_COURSE_CATEGORIES",
    CACHE_KEY_COURSES: "CACHE_KEY_COURSES",
    CACHE_KEY_SUBJECTS: "CACHE_KEY_SUBJECTS",
    CACHE_KEY_PAYMENT_GATEWAY_PAYLOADS: "CACHE_KEY_PAYMENT_GATEWAY_PAYLOADS",

    AUTHORITIES: {
        READ_CHAPTERS_TEST: "READ_CHAPTERS_TEST",
        READ_CHAPTERS: "READ_CHAPTERS",
        DELETE_CHAPTERS: "DELETE_CHAPTERS",
        UPDATE_CHAPTERS_VIEW_INDEXES: "UPDATE_CHAPTERS_VIEW_INDEXES",
        READ_CHAPTERS_MEDIA: "READ_CHAPTERS_MEDIA",
        UPDATE_CHAPTERS: "UPDATE_CHAPTERS",
        CREATE_CHAPTERS: "CREATE_CHAPTERS",

        UPDATE_USER: "UPDATE_USER",
        CREATE_USER: "CREATE_USER",
        READ_USER: "READ_USER",
        READ_USER_ENROLLMENT_COURSES: "READ_USER_ENROLLMENT_COURSES",
        READ_USER_CHAPTERS_TEST_CATALOGUE: "READ_USER_CHAPTERS_TEST_CATALOGUE",
        READ_USER_INQUIRIES: "READ_USER_INQUIRIES",
        READ_USER_ENROLLMENTS: "READ_USER_ENROLLMENTS",
        READ_USER_DEVICES: "READ_USER_DEVICES",
        READ_USER_WALLET_TRANSACTIONS: "READ_USER_WALLET_TRANSACTIONS",
        READ_USER_ROLES: "READ_USER_ROLES",

        CREATE_USER_ROLES: "CREATE_USER_ROLES",
        DELETE_USER_ROLES: "DELETE_USER_ROLES",

        UPDATE_SUBJECTS: "UPDATE_SUBJECTS",
        READ_SUBJECTS: "READ_SUBJECTS",
        READ_SUBJECTS_CHAPTERS: "READ_SUBJECTS_CHAPTERS",
        CREATE_COURSE_SUBJECTS: "CREATE_COURSE_SUBJECTS",

        DELETE_ROLES: "DELETE_ROLES",
        READ_ROLES_AUTHORITIES: "READ_ROLES_AUTHORITIES",
        UPDATE_ROLES: "UPDATE_ROLES",
        CREATE_ROLES: "CREATE_ROLES",

        CREATE_ROLES_AUTHORITIES: "CREATE_ROLES_AUTHORITIES",
        DELETE_ROLES_AUTHORITIES: "DELETE_ROLES_AUTHORITIES",

        CREATE_MEDIA: "CREATE_MEDIA",
        UPDATE_MEDIA: "UPDATE_MEDIA",
        DELETE_MEDIA: "DELETE_MEDIA",
        READ_MEDIA: "READ_MEDIA",

        CREATE_WALLET_TRANSACTION: "CREATE_WALLET_TRANSACTION",

        CREATE_INQUIRY_NOTE: "CREATE_INQUIRY_NOTE",
        DELETE_INQUIRY_NOTE: "DELETE_INQUIRY_NOTE",

        CREATE_INQUIRY: "CREATE_INQUIRY",
        UPDATE_INQUIRY: "UPDATE_INQUIRY",
        DELETE_INQUIRY: "DELETE_INQUIRY",
        READ_INQUIRY_NOTE: "READ_INQUIRY_NOTE",

        UPDATE_ENROLLMENT: "UPDATE_ENROLLMENT",
        CREATE_ENROLLMENT: "CREATE_ENROLLMENT",
        READ_ENROLLMENT_TRANSACTION: "READ_ENROLLMENT_TRANSACTION",
        READ_ENROLLMENT_COURSE: "READ_ENROLLMENT_COURSE",

        READ_ENROLLMENT_TRANSACTION: "READ_ENROLLMENT_TRANSACTION",
        READ_ENROLLMENT_SUMMARY: "READ_ENROLLMENT_SUMMARY",
        CREATE_ENROLLMENT_TRANSACTION: "CREATE_ENROLLMENT_TRANSACTION",

        CREATE_ENROLLMENT_COURSE: "CREATE_ENROLLMENT_COURSE",
        DELETE_ENROLLMENT_COURSE: "DELETE_ENROLLMENT_COURSE",

        UPDATE_USER_DEVICE: "UPDATE_USER_DEVICE",

        CREATE_COURSE: "CREATE_COURSE",
        DELETE_COURSE: "DELETE_COURSE",
        UPDATE_COURSE_VIEW_INDEX: "UPDATE_COURSE_VIEW_INDEX",
        UPDATE_COURSE: "UPDATE_COURSE",
        READ_COURSE: "READ_COURSE",

        UPDATE_COURSE_SUBJECT_VIEW_INDEX: "UPDATE_COURSE_SUBJECT_VIEW_INDEX",
        CREATE_COURSE_SUBJECT: "CREATE_COURSE_SUBJECT",
        DELETE_COURSE_SUBJECT: "DELETE_COURSE_SUBJECT",

        READ_COURSE_CATEGORY: "READ_COURSE_CATEGORY",
        CREATE_COURSE_CATEGORY: "CREATE_COURSE_CATEGORY",
        DELETE_COURSE_CATEGORY: "DELETE_COURSE_CATEGORY",
        UPDATE_COURSE_CATEGORY_VIEW_INDEX: "UPDATE_COURSE_CATEGORY_VIEW_INDEX",
        READ_COURSE_BY_CATEGORY: "READ_COURSE_BY_CATEGORY",

        READ_COUPON_CODE: "READ_COUPON_CODE",
        DELETE_COUPON_CODE: "DELETE_COUPON_CODE",
        UPDATE_COUPON_CODE: "UPDATE_COUPON_CODE",
        CREATE_COUPON_CODE: "CREATE_COUPON_CODE",

        CREATE_COUPON_CODE_COURSES: "CREATE_COUPON_CODE_COURSES",
        DELETE_COUPON_CODE_COURSES: "DELETE_COUPON_CODE_COURSES",
        UPDATE_COUPON_CODE_COURSES: "UPDATE_COUPON_CODE_COURSES",

        CREATE_CHAPTER_TYPES: "CREATE_CHAPTER_TYPES",
        UPDATE_CHAPTER_TYPES_VIEW_INDEXES: "UPDATE_CHAPTER_TYPES_VIEW_INDEXES",
        UPDATE_CHAPTER_TYPES: "UPDATE_CHAPTER_TYPES",
        DELETE_CHAPTER_TYPES: "DELETE_CHAPTER_TYPES",

        DELETE_AUTHORITIES: "DELETE_AUTHORITIES",
        CREATE_AUTHORITIES: "CREATE_AUTHORITIES",
    },
};
